spring:
  config:
    activate:
      on-profile: dockerlocal
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/bioracer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[default_schema]": bioracer

springdoc:
  server-url: ${API_URL}

cors:
  allowed-origins:
    - ${API_URL}
