spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: bioracerBackend
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 210MB

server:
  port: ${SERVER_PORT}
