spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:54321/bioracer?currentSchema=bioracer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        "[default_schema]": bioracer
        "[auto_quote_keyword]": true
        "[format_sql]": true
    hibernate:
      ddl-auto: create-drop
springdoc:
  server-url: ${API_URL}

cors:
  allowed-origins:
    - ${API_URL}
    - ${STUDIO_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
