spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: bioracerBackends

  codec:
    max-in-memory-size: 50MB

upload:
  server:
    url: ${PUBLIC_URL_BASE}
server:
  port: ${SERVER_PORT}
