spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/bioracer?currentSchema=bioracer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[default_schema]": bioracer

springdoc:
  server-url: ${API_URL}

cors:
  allowed-origins:
    - ${API_URL}
    - ${STUDIO_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
