package Bioracer.BachelorProject.Backend.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.nio.charset.StandardCharsets;
import java.time.Duration;

import javax.crypto.spec.SecretKeySpec;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.security.oauth2.jose.jws.MacAlgorithm;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtException;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.jwt.NimbusJwtEncoder;

import com.nimbusds.jose.jwk.source.ImmutableSecret;

import Bioracer.BachelorProject.Backend.config.JwtProperties;
import Bioracer.BachelorProject.Backend.model.Role;

/**
 * Round-trip tests with a real HS256 encoder and decoder: tokens generated by
 * the service must be genuinely decodable, and invalid tokens must be
 * rejected.
 */
class JwtServiceRoundTripTest {

    private static final String SECRET = "0123456789abcdef0123456789abcdef";

    private SecretKeySpec secretKey;
    private JwtService jwtService;

    @BeforeEach
    void setUp() {
        secretKey = new SecretKeySpec(SECRET.getBytes(StandardCharsets.UTF_8), "HmacSHA256");
        jwtService = jwtServiceWithLifetime(Duration.ofHours(8));
    }

    private JwtService jwtServiceWithLifetime(Duration lifetime) {
        JwtEncoder encoder = new NimbusJwtEncoder(new ImmutableSecret<>(secretKey));
        JwtDecoder decoder = NimbusJwtDecoder.withSecretKey(secretKey).macAlgorithm(MacAlgorithm.HS256).build();
        JwtProperties properties = new JwtProperties(SECRET, new JwtProperties.Token("Bioracer_Backend", lifetime));
        return new JwtService(properties, encoder, decoder);
    }

    @Test
    void generatedTokenRoundTripsEmail() {
        String token = jwtService.generateToken("jane@example.com", 1000L, Role.USER);

        assertThat(jwtService.extractEmail(token)).isEqualTo("jane@example.com");
    }

    @Test
    void generatedTokenRoundTripsRole() {
        String userToken = jwtService.generateToken("jane@example.com", 1000L, Role.USER);
        String adminToken = jwtService.generateToken("admin@example.com", 1L, Role.ADMIN);

        assertThat(jwtService.extractRole(userToken)).isEqualTo("ROLE_USER");
        assertThat(jwtService.extractRole(adminToken)).isEqualTo("ROLE_ADMIN");
    }

    @Test
    void generatedTokenRoundTripsId() {
        String token = jwtService.generateToken("jane@example.com", 1000L, Role.USER);

        assertThat(jwtService.extractId(token)).isEqualTo(1000L);
    }

    @Test
    void tamperedTokenIsRejected() {
        String token = jwtService.generateToken("jane@example.com", 1000L, Role.USER);
        String tampered = token.substring(0, token.length() - 4) + "AAAA";

        assertThatThrownBy(() -> jwtService.extractEmail(tampered))
                .isInstanceOf(JwtException.class);
    }

}
