name: Deploy to Azure

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Get latest package version URL
        id: get-download-url
        run: |
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://maven.pkg.github.com/UcllSoftwareEngineering2425/backend-ti18/be.ucll.se.team18/courses-backend/0.0.1-SNAPSHOT/maven-metadata.xml

          LATEST_VERSION=$(grep -oP '<snapshotVersion>.*<extension>jar</extension>.*<value>([^<]+)</value>' maven-metadata.xml | sed -E 's/.*<value>([^<]+)<\/value>.*/\1/')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Download artifact from GitHub Packages
        run: |
          curl -L -O -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://maven.pkg.github.com/UcllSoftwareEngineering2425/backend-ti18/be.ucll.se.team18/courses-backend/0.0.1-SNAPSHOT/courses-backend-${{env.LATEST_VERSION}}.jar"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "TI18-backend"
          package: "*.jar"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FB50E9E040054DA7A77759D18D0662AD }}
