name: Docker Image Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t bioracer-backend .

      - name: Login to Docker Hub using PAT
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag bioracer-backend:latest sennebeeckman/bioracer-backend:latest

      - name: Push Docker image
        run: docker push sennebeeckman/bioracer-backend:latest
